apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podlister

labels:
- includeSelectors: true
  pairs:
    app: podlister

resources:
- namespace.yaml
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- buildconfig.yaml
- imagestream.yaml
- clusterrole.yaml
- clusterrolebinding.yaml

configurations:
- nameReference.yaml
