apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: podlister
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- buildconfig.yaml
- imagestream.yaml

configurations:
  - nameReference.yaml
