apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: podlister

resources:
- ../../base

patches:
- patch: |
    apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: podlister
    spec:
      source:
        git:
          uri: https://github.com/larsks/podlister.git

secretGenerator:
- name: github-buildconfig
  envs:
  - github-buildconfig.env
