apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app: podlister
    includeSelectors: true

resources:
- ../../base

patches:
- patch: |
    apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: podlister
    spec:
      source:
        git:
          uri: https://github.com/larsks/podlister.git

secretGenerator:
- name: github-buildconfig
  options:
    disableNameSuffixHash: true
  envs:
  - github-buildconfig.env
